/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;
import AeroPorto.Voo;
import Utils.FiltrarCampo;
import Utils.FormUtils;
import static Utils.FormUtils.validaData;
import static Utils.FormUtils.validaHora;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Cleo
 */
public class FormAdicionarVoo extends javax.swing.JInternalFrame {
    protected ArrayList<Voo> voo = new ArrayList<>();
    
    /**
     * Creates new form FormAdicionarVoo
     */
    
    private static FormAdicionarVoo telaVoo;
    
    public static FormAdicionarVoo getInstancia(){
        if(telaVoo== null){
            telaVoo = new FormAdicionarVoo();  
        }
        return telaVoo;
    }
     
        
    public final void limparCampos(){
        //Limpa todos os campos de texto
        vooPartida.setText(null);
        vooData.setText(null);
        vooHora.setText(null);
        vooDestino.setText(null);
        vooPartida.setText(null);
        vooPreco.setText(null);
    }
    
    //Adiciona novo vôo
    public final void adicionar(){
        //Verificação se é uma Data válida
        if(!validaData(vooData.getText())){
            JOptionPane.showMessageDialog(null,"Data inválida!!!","Erro",2);
        }
        //Verificação se é uma Hora válida
        else if(!validaHora(vooHora.getText())){
            JOptionPane.showMessageDialog(null,"Hora inválida!!!","Erro",2);
        }
        else{
            //Verifica se algum campo está em branco
            String msg = "";

            msg += FormUtils.validarCampos(vooCod, "Cód Vôo");
            msg += FormUtils.validarCampos(vooData, "Data");
            msg += FormUtils.validarCampos(vooHora, "Hora");    
            msg += FormUtils.validarCampos(vooPartida, "Partida");
            msg += FormUtils.validarCampos(vooDestino, "Destino");
            msg += FormUtils.validarCampos(vooPreco, "Preco");
            if(!msg.isEmpty()){
                //Exibe a mensagem de qual campo está em branco
                JOptionPane.showMessageDialog(null,msg,"Erro",2);
            }  else{   
                //Cria a nova instância da classe vôo
                Voo voo1 = new Voo(vooCod.getText(), vooData.getText(), vooHora.getText(), vooPartida.getText(), vooDestino.getText(), Double.valueOf(vooPreco.getText()));
                
                //Adiciona ao arrayList voo o voo1
                voo.add(voo1);
                
                //Preenche a tabela
                FormUtils.preencherTabela(tableVoo, voo);
                
                //Adiciona o número do voo no combobox do formulario FormVendaPassagens
                FormVendaPassagens.getInstancia().AdicionarVoosCombobox(vooCod.getText());
                
                //limpa os campos
                limparCampos();
            }
        }
    }
    
    public FormAdicionarVoo() {
        initComponents();
        
        //Configura o formulario como fechavel
        setClosable(true);
        
        //Filtragem dos campos de imput
        vooCod.setDocument(new FiltrarCampo("Int"));
        vooPreco.setDocument(new FiltrarCampo("Int"));
        vooPartida.setDocument(new FiltrarCampo("Str"));
        vooDestino.setDocument(new FiltrarCampo("Str"));

        //Criação dos vôos como modelo
        Voo voo1 = new Voo("125", "03/01/21", "20:42", "Belém", "São Paulo", 987.30);
        Voo voo2 = new Voo("126", "03/01/21", "21:42", "Belém", "São Paulo", 987.30);
        Voo voo3 = new Voo("127", "03/01/21", "22:42", "Belém", "São Paulo", 987.30);
        FormVendaPassagens.getInstancia().AdicionarVoosCombobox(voo1.getNumVoo());
        FormVendaPassagens.getInstancia().AdicionarVoosCombobox(voo2.getNumVoo());
        FormVendaPassagens.getInstancia().AdicionarVoosCombobox(voo3.getNumVoo());
        voo.add(voo1);
        voo.add(voo2);
        voo.add(voo3);
  
        //Preechimento da tabela
        FormUtils.preencherTabela(tableVoo, voo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        vooPartida = new javax.swing.JTextField();
        vooData = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        vooHora = new javax.swing.JFormattedTextField();
        vooCod = new javax.swing.JTextField();
        vooDestino = new javax.swing.JTextField();
        vooPreco = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVoo = new javax.swing.JTable();

        setBorder(null);
        setTitle("ADICIONAR VÔO");

        jButton1.setText("COMFIRMAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try {
            vooData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vooData.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jLabel3.setText("HORA");

        try {
            vooHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vooHora.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        jLabel7.setText("PARTIDA");

        jLabel8.setText("DESTINO");

        jLabel9.setText("PREÇO");

        jLabel10.setText("DATA");

        jLabel11.setText("CÓD VOO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vooCod)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vooData, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(vooHora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addComponent(vooPartida)
                    .addComponent(vooPreco)
                    .addComponent(vooDestino))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(vooCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(vooData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(vooHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vooPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vooDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vooPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(tableVoo);
        if (tableVoo.getColumnModel().getColumnCount() > 0) {
            tableVoo.getColumnModel().getColumn(0).setResizable(false);
            tableVoo.getColumnModel().getColumn(1).setResizable(false);
            tableVoo.getColumnModel().getColumn(2).setResizable(false);
            tableVoo.getColumnModel().getColumn(3).setResizable(false);
            tableVoo.getColumnModel().getColumn(4).setResizable(false);
            tableVoo.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // chama o método de adicionar o vôo quando clicado
         adicionar();
    }//GEN-LAST:event_jButton1ActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVoo;
    private javax.swing.JTextField vooCod;
    private javax.swing.JFormattedTextField vooData;
    private javax.swing.JTextField vooDestino;
    private javax.swing.JFormattedTextField vooHora;
    private javax.swing.JTextField vooPartida;
    private javax.swing.JTextField vooPreco;
    // End of variables declaration//GEN-END:variables
}
